name: Placeholder stage name

on:
  workflow_call:
    # inputs:
    #   environment:
    #     required: true
    #     type: string
    # secrets:
    #   API_KEY:
    #     required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4

  job-semver-next:
    runs-on: ubuntu-latest
    needs: checkout
    # environment: ${{ inputs.environment }}
    steps:
    - name: Run local action
      id: custom-action1
      uses: open-appdev-lab/ansible-collections-ci/.github/actions/semver-next@beta
      with:
        placeholder-input1: 'GitHub Actions'

    - name: Print Output
    #   env:
    #     KEY: ${{ secrets.API_KEY }}
      run: echo " The random number was ${{ steps.custom-action1.outputs.placeholder-output1 }}"

  job-ansible-validate-tokens:
    runs-on: ubuntu-latest
    needs: checkout
    # environment: ${{ inputs.environment }}
    steps:

    - name: Run local action
      id: custom-action2
      uses: open-appdev-lab/ansible-collections-ci/.github/actions/dummy@beta
      with:
        placeholder-input1: 'GitHub Actions'

    - name: Print Output
    #   env:
    #     KEY: ${{ secrets.API_KEY }}
      run: echo " The random number was ${{ steps.custom-action1.outputs.placeholder-output1 }}"

  job-ansible-collection-install:
    runs-on: ubuntu-latest
    needs: checkout
    # environment: ${{ inputs.environment }}
    steps:

    - name: Run local action
      id: custom-action3
      uses: open-appdev-lab/ansible-collections-ci/.github/actions/dummy@beta
      with:
        placeholder-input1: 'GitHub Actions'

    - name: Print Output
    #   env:
    #     KEY: ${{ secrets.API_KEY }}
      run: echo " The random number was ${{ steps.custom-action1.outputs.placeholder-output1 }}"
