name: Placeholder stage name

on:
  workflow_call:
    # inputs:
    #   environment:
    #     required: true
    #     type: string
    # secrets:
    #   API_KEY:
    #     required: true

jobs:
  custom-secret-detection:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment }}
    steps:
      # 1. Checkout the Caller Repo (standard)
      - name: Checkout Application Code
        uses: actions/checkout@v4
        with:
          path: app-code # Checkout to a subfolder to avoid conflicts

      # 2. Checkout the CI Repo (where your scripts live)
      - name: Checkout CI Tools
        uses: actions/checkout@v4
        with:
          repository: my-org/ci-repo
          ref: main # Or use a specific tag/branch
          path: ci-tools # Critical: Checkout to a specific folder

      - name: Run local action
        id: custom-action1
        uses: ./ci-tools/.github/actions/dummy
        with:
          placeholder-input1: 'GitHub Actions'

      - name: Print Output
      #   env:
      #     KEY: ${{ secrets.API_KEY }}
        run: echo " The random number was ${{ steps.custom-action1.outputs.placeholder-output1 }}"
